/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kambing.ui.ac.id
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMIEAYAMBAKSO = new javax.swing.JCheckBox();
        jCheckBoxBAKSOURAT = new javax.swing.JCheckBox();
        jCheckBoxBAKSOTELUR = new javax.swing.JCheckBox();
        jCheckBoxMIEAYAM = new javax.swing.JCheckBox();
        TOTAL = new javax.swing.JTextField();
        baksourat = new javax.swing.JTextField();
        baksotelur = new javax.swing.JTextField();
        mieayam = new javax.swing.JTextField();
        HITUNG = new javax.swing.JButton();
        HAPUS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mieayambakso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jCheckBoxMIEAYAMBAKSO.setText("Mie Ayam Bakso @ 10000");
        jCheckBoxMIEAYAMBAKSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMIEAYAMBAKSOActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxMIEAYAMBAKSO);
        jCheckBoxMIEAYAMBAKSO.setBounds(90, 280, 190, 30);

        jCheckBoxBAKSOURAT.setText("Bakso Urat @ Rp. 8000");
        jCheckBoxBAKSOURAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBAKSOURATActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxBAKSOURAT);
        jCheckBoxBAKSOURAT.setBounds(90, 90, 190, 30);

        jCheckBoxBAKSOTELUR.setText("Bakso Telur @ Rp. 8000");
        jCheckBoxBAKSOTELUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBAKSOTELURActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxBAKSOTELUR);
        jCheckBoxBAKSOTELUR.setBounds(90, 150, 170, 30);

        jCheckBoxMIEAYAM.setText("Mie Ayam @ Rp. 7000");
        jCheckBoxMIEAYAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMIEAYAMActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxMIEAYAM);
        jCheckBoxMIEAYAM.setBounds(90, 220, 180, 30);
        getContentPane().add(TOTAL);
        TOTAL.setBounds(320, 410, 140, 30);
        getContentPane().add(baksourat);
        baksourat.setBounds(290, 90, 140, 30);

        baksotelur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baksotelurActionPerformed(evt);
            }
        });
        getContentPane().add(baksotelur);
        baksotelur.setBounds(290, 150, 140, 30);

        mieayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mieayamActionPerformed(evt);
            }
        });
        getContentPane().add(mieayam);
        mieayam.setBounds(290, 220, 140, 30);

        HITUNG.setText("HITUNG");
        HITUNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HITUNGActionPerformed(evt);
            }
        });
        getContentPane().add(HITUNG);
        HITUNG.setBounds(260, 350, 90, 23);

        HAPUS.setText("HAPUS");
        HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HAPUSActionPerformed(evt);
            }
        });
        getContentPane().add(HAPUS);
        HAPUS.setBounds(400, 350, 90, 23);

        jLabel1.setText("JUMLAH HARGA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 420, 80, 14);
        getContentPane().add(mieayambakso);
        mieayambakso.setBounds(290, 280, 140, 30);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("KANTIN PAK YO TOK!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 30, 180, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMIEAYAMBAKSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMIEAYAMBAKSOActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxMIEAYAMBAKSO.isSelected() == true){
            mieayambakso.setEditable(true);
        }else{
            mieayambakso.setEditable(false);
            mieayambakso.setText("");
        }
    }//GEN-LAST:event_jCheckBoxMIEAYAMBAKSOActionPerformed

    private void jCheckBoxBAKSOURATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBAKSOURATActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxBAKSOURAT.isSelected() == true){
            baksourat.setEditable(true);
        }else{
            baksourat.setEditable(false);
            baksourat.setText("");
        }
    }//GEN-LAST:event_jCheckBoxBAKSOURATActionPerformed

    private void jCheckBoxBAKSOTELURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBAKSOTELURActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxBAKSOTELUR.isSelected() == true){
            baksotelur.setEditable(true);
        }else{
            baksotelur.setEditable(false);
            baksotelur.setText("");
        }
    }//GEN-LAST:event_jCheckBoxBAKSOTELURActionPerformed

    private void jCheckBoxMIEAYAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMIEAYAMActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxMIEAYAM.isSelected() == true){
            mieayam.setEditable(true);
        }else{
            mieayam.setEditable(false);
            mieayam.setText("");
        }
    }//GEN-LAST:event_jCheckBoxMIEAYAMActionPerformed

    private void baksotelurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baksotelurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baksotelurActionPerformed

    private void mieayamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mieayamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mieayamActionPerformed

    private void HITUNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HITUNGActionPerformed
        // TODO add your handling code here:
        int total = 0;
        if (jCheckBoxBAKSOURAT.isSelected()) {
            String BU = baksourat.getText();
            int jumlahBU = Integer.parseInt(BU);
            int hargaBU = jumlahBU * 8000;
            total = total + hargaBU;
        }
        if (jCheckBoxBAKSOTELUR.isSelected()) {
            String BT = baksotelur.getText();
            int jumlahBT = Integer.parseInt(BT);
            int hargaBT = jumlahBT * 8000;
            total = total + hargaBT;
        }
        if (jCheckBoxMIEAYAM.isSelected()) {
            String MA = mieayam.getText();
            int jumlahMA = Integer.parseInt(MA);
            int hargaMA = jumlahMA * 7000;
            total = total + hargaMA;
        }
        if (jCheckBoxMIEAYAMBAKSO.isSelected()) {
            String MAB = mieayambakso.getText();
            int jumlahMAB = Integer.parseInt(MAB);
            int hargaMAB = jumlahMAB * 10000;
            total = total + hargaMAB;
        }
        TOTAL.setText(""+total);
    }//GEN-LAST:event_HITUNGActionPerformed

    private void HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HAPUSActionPerformed
        // TODO add your handling code here:
        baksourat.setEditable(false);
        baksourat.setText("");
        
        baksotelur.setEditable(false);
        baksotelur.setText("");
        
        mieayam.setEditable(false);
        mieayam.setText("");
        
        mieayambakso.setEditable(false);
        mieayambakso.setText("");
        
        TOTAL.setText("");
    }//GEN-LAST:event_HAPUSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HAPUS;
    private javax.swing.JButton HITUNG;
    private javax.swing.JTextField TOTAL;
    private javax.swing.JTextField baksotelur;
    private javax.swing.JTextField baksourat;
    private javax.swing.JCheckBox jCheckBoxBAKSOTELUR;
    private javax.swing.JCheckBox jCheckBoxBAKSOURAT;
    private javax.swing.JCheckBox jCheckBoxMIEAYAM;
    private javax.swing.JCheckBox jCheckBoxMIEAYAMBAKSO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField mieayam;
    private javax.swing.JTextField mieayambakso;
    // End of variables declaration//GEN-END:variables
}
